import json
import pathlib
import sys
from typing import Any

# ---------------------------------------------------------------------------
# Ensure project root is importable when running pytest
# ---------------------------------------------------------------------------
PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    import pytest
except ImportError:  # pragma: no cover - tooling only
    pytest = None

# ---------------------------------------------------------------------------
# Imports from application (NO HTTP, NO FastAPI startup)
# NOTE: E402 is intentional here because sys.path must be patched first.
# ---------------------------------------------------------------------------
from routes import vendor_rt_inventory_routes as vrt_routes  # noqa: E402
from services.vendor_rt_inventory_state import (  # noqa: E402
    DEFAULT_CATALOG_DB_PATH,
    get_checkpoint,
    get_state_max_end_time,
    get_state_rows,
)

# ---------------------------------------------------------------------------
# Paths / constants
# ---------------------------------------------------------------------------
ROOT = pathlib.Path(__file__).resolve().parent
GOLDEN_DIR = ROOT / "golden"
VENDOR_PO_CACHE = PROJECT_ROOT / "vendor_pos_cache.json"
DEFAULT_MARKETPLACE_ID = "A2VIGQ35RCS4UG"

# ---------------------------------------------------------------------------
# Golden helpers
# ---------------------------------------------------------------------------
def _load_json_allow_comments(path: pathlib.Path) -> Any:
    """
    Load JSON while allowing // comments.
    Returns None if file is missing, empty, or comment-only.
    """
    if not path.exists():
        return None

    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return None

    lines = [line for line in text.splitlines() if not line.strip().startswith("//")]
    if not lines:
        return None

    return json.loads("\n".join(lines))


def load_golden_json(name: str) -> Any:
    return _load_json_allow_comments(GOLDEN_DIR / name)


def normalize_json(payload: Any) -> Any:
    """
    Deterministic normalization so ordering changes do not break tests.
    """
    if isinstance(payload, dict):
        return {k: normalize_json(payload[k]) for k in sorted(payload.keys())}

    if isinstance(payload, list):
        normalized = [normalize_json(item) for item in payload]
        normalized.sort(key=lambda item: json.dumps(item, sort_keys=True))
        return normalized

    return payload


def write_golden(name: str, payload: Any) -> None:
    """
    Write golden baseline once, with a banner.
    """
    path = GOLDEN_DIR / name
    serialized = json.dumps(payload, indent=2, sort_keys=True)
    banner = "// Golden baseline generated by tests/test_golden_outputs.py\n"
    path.write_text(banner + serialized + "\n", encoding="utf-8")

# ---------------------------------------------------------------------------
# Snapshot capture (READ-ONLY)
# ---------------------------------------------------------------------------
def capture_rt_inventory_snapshot(
    marketplace_id: str = DEFAULT_MARKETPLACE_ID,
) -> Any:
    """
    Capture RT inventory snapshot using cached/local state only.
    No HTTP, no API calls, no DB writes.
    """
    db_path = pathlib.Path(DEFAULT_CATALOG_DB_PATH)

    as_of = get_checkpoint(marketplace_id, db_path=db_path)
    if not as_of:
        as_of = get_state_max_end_time(marketplace_id, db_path=db_path)

    items = get_state_rows(marketplace_id, db_path=db_path)
    vrt_routes._decorate_inventory_items(items, marketplace_id, db_path)

    payload = {
        "marketplace_id": marketplace_id,
        "as_of": as_of,
        "items": items,
    }
    return normalize_json(payload)


def capture_vendor_po_snapshot() -> Any:
    """
    Capture Vendor PO snapshot from local cache only.
    """
    if not VENDOR_PO_CACHE.exists():
        raise AssertionError(f"Missing vendor PO cache file: {VENDOR_PO_CACHE}")

    raw = json.loads(VENDOR_PO_CACHE.read_text(encoding="utf-8"))

    payload = {
        "items": (
            raw
            if isinstance(raw, list)
            else raw.get("items")
            if isinstance(raw, dict)
            else raw
        ),
        "meta": {
            "source": "vendor_pos_cache.json",
            "size": VENDOR_PO_CACHE.stat().st_size,
        },
    }
    return normalize_json(payload)

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
@pytest.mark.skipif(pytest is None, reason="pytest not installed; TODO: install pytest for golden tests")
def test_rt_inventory_golden():
    actual = capture_rt_inventory_snapshot()
    expected = load_golden_json("rt_inventory_expected.json")

    if expected is None:
        write_golden("rt_inventory_expected.json", actual)
        pytest.fail("Golden snapshot baseline created; review and re-run")

    assert actual == expected, "RT inventory output diverged from golden snapshot"


@pytest.mark.skipif(pytest is None, reason="pytest not installed; TODO: install pytest for golden tests")
def test_vendor_po_golden():
    actual = capture_vendor_po_snapshot()
    expected = load_golden_json("vendor_po_expected.json")

    if expected is None:
        write_golden("vendor_po_expected.json", actual)
        pytest.fail("Golden snapshot baseline created; review and re-run")

    assert actual == expected, "Vendor PO output diverged from golden snapshot"
