import json
import pathlib
import sys
from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# Ensure project root is importable when running pytest
# ---------------------------------------------------------------------------
PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    import pytest
except ImportError:  # pragma: no cover
    pytest = None

# ---------------------------------------------------------------------------
# Imports from application (NO HTTP, NO FastAPI startup)
# ---------------------------------------------------------------------------
from services.catalog_images import attach_image_urls  # noqa: E402
from services.vendor_inventory_realtime import (  # noqa: E402
    decorate_items_with_sales,
    load_sales_30d_map,
)
from services.vendor_rt_inventory_state import (  # noqa: E402
    DEFAULT_CATALOG_DB_PATH,
    get_state_rows,
)

# ---------------------------------------------------------------------------
# Paths / constants
# ---------------------------------------------------------------------------
ROOT = pathlib.Path(__file__).resolve().parent
GOLDEN_DIR = ROOT / "golden"
VENDOR_PO_CACHE = PROJECT_ROOT / "vendor_pos_cache.json"
DEFAULT_MARKETPLACE_ID = "A2VIGQ35RCS4UG"


# ---------------------------------------------------------------------------
# Golden helpers
# ---------------------------------------------------------------------------
def _load_json_allow_comments(path: pathlib.Path) -> Any:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return None
    lines = [ln for ln in text.splitlines() if not ln.strip().startswith("//")]
    if not lines:
        return None
    return json.loads("\n".join(lines))


def load_golden_json(name: str) -> Any:
    return _load_json_allow_comments(GOLDEN_DIR / name)


def write_golden(name: str, payload: Any) -> None:
    path = GOLDEN_DIR / name
    serialized = json.dumps(payload, indent=2, sort_keys=True)
    banner = "// Golden baseline generated by tests/test_golden_outputs.py\n"
    path.write_text(banner + serialized + "\n", encoding="utf-8")


def normalize_json(payload: Any) -> Any:
    if isinstance(payload, dict):
        return {k: normalize_json(payload[k]) for k in sorted(payload.keys())}
    if isinstance(payload, list):
        normalized = [normalize_json(x) for x in payload]
        normalized.sort(key=lambda x: json.dumps(x, sort_keys=True))
        return normalized
    return payload


# ---------------------------------------------------------------------------
# Stable projections (THIS is the key change)
# ---------------------------------------------------------------------------
def project_rt_inventory(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Keep only stable-ish fields so goldens don't drift with quantities/timestamps.

    If you want stricter goldens later, add fields intentionally.
    """
    projected: List[Dict[str, Any]] = []
    for it in items:
        if not isinstance(it, dict):
            continue
        projected.append(
            {
                "asin": it.get("asin"),
                "imageUrl": it.get("imageUrl"),
                # Optional: include title if you want to detect catalog/title regressions
                "title": it.get("title"),
                # Optional: include sales_30d presence (not value) if you want
                "has_sales_30d": it.get("sales_30d") is not None,
            }
        )
    return projected


def project_vendor_pos(raw_items: Any) -> List[str]:
    """
    Reduce Vendor PO snapshot to stable identifiers.
    """
    items = raw_items if isinstance(raw_items, list) else []
    po_numbers: List[str] = []

    for it in items:
        if not isinstance(it, dict):
            continue
        # Many of your payloads use orderDetails.purchaseOrderNumber
        od = it.get("orderDetails") if isinstance(it.get("orderDetails"), dict) else {}
        po = od.get("purchaseOrderNumber") or it.get("purchaseOrderNumber") or it.get("po_number")
        if po:
            po_numbers.append(str(po))

    # Deduplicate + stable order
    return sorted(set(po_numbers))


# ---------------------------------------------------------------------------
# Snapshot capture (READ-ONLY)
# ---------------------------------------------------------------------------
def capture_rt_inventory_projection(marketplace_id: str = DEFAULT_MARKETPLACE_ID) -> Any:
    db_path = pathlib.Path(DEFAULT_CATALOG_DB_PATH)
    items = get_state_rows(marketplace_id, db_path=db_path)

    # decorate (read-only)
    attach_image_urls(items)
    sales_30d_map = load_sales_30d_map(str(db_path))  # str() avoids WindowsPath bind issues
    decorate_items_with_sales(items, sales_30d_map)

    payload = {
        "marketplace_id": marketplace_id,
        "items_projected": project_rt_inventory(items),
    }
    return normalize_json(payload)


def capture_vendor_po_projection() -> Any:
    if not VENDOR_PO_CACHE.exists():
        raise AssertionError(f"Missing vendor PO cache file: {VENDOR_PO_CACHE}")

    raw = json.loads(VENDOR_PO_CACHE.read_text(encoding="utf-8"))

    raw_items = raw if isinstance(raw, list) else raw.get("items") if isinstance(raw, dict) else []
    payload = {
        "po_numbers": project_vendor_pos(raw_items),
        "meta": {"source": "vendor_pos_cache.json"},
    }
    return normalize_json(payload)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
@pytest.mark.skipif(pytest is None, reason="pytest not installed; TODO: install pytest for golden tests")
def test_rt_inventory_golden():
    actual = capture_rt_inventory_projection()
    expected = load_golden_json("rt_inventory_expected.json")

    if expected is None:
        write_golden("rt_inventory_expected.json", actual)
        pytest.fail("Golden snapshot baseline created; review and re-run")

    expected = normalize_json(expected)
    assert actual == expected, "RT inventory projection diverged from golden snapshot"


@pytest.mark.skipif(pytest is None, reason="pytest not installed; TODO: install pytest for golden tests")
def test_vendor_po_golden():
    actual = capture_vendor_po_projection()
    expected = load_golden_json("vendor_po_expected.json")

    if expected is None:
        write_golden("vendor_po_expected.json", actual)
        pytest.fail("Golden snapshot baseline created; review and re-run")

    expected = normalize_json(expected)
    assert actual == expected, "Vendor PO projection diverged from golden snapshot"
